### PR TITLE
need_rebuild(), PATCH1() and more

### PR DESCRIPTION
**Pull request by step-**
This pull request is supposed to include three commits:
 * @step- Merge pull request #1 from wdlkmpx/master … e2f7804  
 * @step- Add (back) PATCH1() and need_rebuild(); other minor changes. See pull… … 1388595
 * @step- Changed way to configure the script and set the build target. Other f… 91ab69e

### Tested and Gist of it

I tested my changes on Fatdog64 with PATCH1 disabled.

I successfully build ffmpeg and mpv from scratch.

### Initialization and use

I changed somewhat how you initialize the build target and run the script. The first set of variables
```
    ffmpeg=2   #0:disable 1:configure&build-all 2:build-changes-only
    mpv=2      #0:disable 1:configure&build-all 2:build-changes-only
    spek=0     #0:disable 1:WIP
    aegisub=0  #0:disable 1:WIP
```
establishes *how* to build each target. *Which* target to build is another story. You can set a default target inside the script:
```
    build=${1:-ffmpeg} #ffmpeg mpv spek aegisub
```
(suggestion: make ffmpeg the default target and don't change it).

When you want to build another target, just pass its name on the command line:
```
    bash -e ./ffmpeg_project.sh mpv

    bash -e ./ffmpeg_project.sh ffmpg && bash -e ./ffmpeg_project.sh mpv
```
The second line above is how you'd build two targets in a sequence. That's because each run of the script can deal with one target at the time, as your recent edits to the code seem to imply -- you have introduced target-specific sub-sections and override some settings based on `$build` values.

### libtheora

Some details from my fatdog script had gone lost. For instance, not building libtheora example programs, which, at least on Fatdog64, fail the make.

### need_rebuild

I added back need_rebuild(). Feel free to push back this change, but this time I tried to explain its benefit. It can save compile time...

### PATCH1

Another change, see PATCH1(). Instead of commenting out the _call_ to PATCH1, I added some code in PATCH1 to skip patching if Fatdog64 isn't the platform - actually, if the script name doesn't include '_fatdog'.

### Cosmetics (not quite)

Your text editor saves empty lines with an initial tab character, that is, the line looks empty but it really isn't. So, I removed all such tabs and left the empty line truly empty. This change can be regarded as simply 'cosmetics' but it isn't because sometimes the extra tabs in empty lines confuse my text comparison tool. I'm not going to fuss about such lines.  But when I find them I change them so my comparison tool works better.

### Indentation

A more important issue is indentation standards. I think it's better if we use the same standard.  Mine is: no tab characters (ctrl+I) at all, just spaces. Each tab stop moves two spaces left (indent) or right (unindent).

Your standard seems to mix tabs and spaces. The first tab stop is indented by a tab character (ctrl+I). Subsequent tab stops are indented by two spaces. Mixing tabs and spaces isn't recommended. I prefer to use either _all_ spaces (my standard) or all _tabs_ (niether mine nor yours).  Which choice?

### Questions

 * Why does ffmpeg
```
	  make
	  [ $? -ne 0 ] && make # Why making again on error ??
	  make install
```
I commented out that block of code and added a modified version.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Sounds good. I'll test your changes later.

It's because I'm lazy, that's why I mix tabs and spaces. Ok only spaces in this script. You may change that...

About your question.. it's because in this machine GCC segfaults in the middle of ffmpeg compiling, but with that extra line it continues compiling until it finishes... don't know... maybe it's about to die, the hard disk makes noises.

**Comment by step-** [comment]
gcc-4.8.2 used to segfault on me too. I have upgraded to 4.8.3. If I recall correctly, it only happened with an Intel processor, and it had something to do with math libraries.
```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-fatdog-linux-gnu/4.8.3/lto-wrapper
Target: x86_64-fatdog-linux-gnu
Configured with: ../gcc-4.8.3/configure --prefix=/usr --libdir=/usr/lib64 --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-system-zlib --enable-lto --enable-languages=c,c++,fortran,go,java,objc,obj-c++ --build=x86_64-fatdog-linux-gnu
Thread model: posix
gcc version 4.8.3 (GCC) 
#
```
Maybe you can add a test for your dying machine... something like
```
make ||
if [ "${build}" = ffmpeg -a `hostname` = dying_computer ]; then make; fi &&
make install && {
  # cp stuff
}
```

**Comment by wdlkmpx** [comment]
I haven't tested your modifications yet. I have to recompile all the ffmpeg stuff... I think the "exlusive stuff" should be reserved for compiling compiling exclusive static ffmpeg executables, as they are not needed for other builds..

**Comment by wdlkmpx** [comment]
It looks like uchardet generates unusable static libs. Have you uncommenting the uchardet code?

If you do, this is how you undo it:

Delete:

build/lib/libuchardet.a
build/lib/pkgconfig/uchardet.pc
build/include/uchardet

Comment out the uchardet code again.

**Comment by step-** [comment]
No, I didn't consciously uncomment uchardet. If I did it's a mistake.

**Pull request merged**
